src/AarhusWebDevCoopVbj/ViewModels/ContactForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AarhusWebDevCoopVbj.ViewModels
{
    
        public class ContactForm
        {
            [Required]
            public string Name { get; set; }
            [Required]
            [EmailAddress(ErrorMessage = "This is not a valid email address")]
            public string Email { get; set; }
            [Required]
            public string Subject { get; set; }
            [Required]
            public string Message { get; set; }
        }
    
}

src/AarhusWebDevCoopVbj/Controllers/ContactFormSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using AarhusWebDevCoopVbj.ViewModels;
using Umbraco.Core.Models;
using Umbraco.Web.Mvc;

namespace AarhusWebDevCoopVbj.Controllers
{
    public class ContactFormSurfaceController : SurfaceController
    {
        public ActionResult Index()
        {
            return PartialView("ContactForm", new ContactForm());
        }

        [HttpPost]
        public ActionResult HandleFormSubmit(ContactForm model)
        {
            if (!ModelState.IsValid)
            {
                return CurrentUmbracoPage();
            }
            {
                // sender mail
               /* MailMessage message = new MailMessage();
                message.To.Add("vickibuhl86@gmail.com");
                message.Subject = model.Subject;
                message.From = new MailAddress(model.Email, model.Name);
                message.Body = model.Message + "\n my email is: " + model.Email;
                */
                // mailopsætning
               /* using (SmtpClient smtp = new SmtpClient())
                {
                    smtp.DeliveryMethod = SmtpDeliveryMethod.Network; smtp.UseDefaultCredentials = false;
                    smtp.EnableSsl = true;
                    smtp.Host = "smtp.gmail.com"; smtp.Port = 587;
                    smtp.Credentials = new System.Net.NetworkCredential("vickibuhl86@gmail.com", "vtuucuephckczoav");
                    smtp.EnableSsl = true;

                    smtp.Send(message);
                }*/

                TempData["success"] = true;

                IContent comment = Services.ContentService.CreateContent(model.Subject, CurrentPage.Id, "Comment");

                comment.SetValue("name", model.Name);
                comment.SetValue("email", model.Email);
                comment.SetValue("subject", model.Subject);
                comment.SetValue("message", model.Message);

                // Save
                Services.ContentService.Save(comment);

                //Save and publish
                //Services.ContentService.SaveAndPublishWithStatus(comment);

                return RedirectToCurrentUmbracoPage();
            }

            

            

        }
    }
}

src/AarhusWebDevCoopVbj/Views/ArticlesItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

<h1>@Umbraco.Field("articlesItemTitle")</h1>
	<p>@Umbraco.Field("articleItemContent")</p>
	<div>Author: @Umbraco.Field("articleItemAuthor")</div>

src/AarhusWebDevCoopVbj/Views/ArticlesMain.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

<h1>@Umbraco.Field("articlesTitle")</h1>
	<p>@Umbraco.Field("articlesContents")</p>
	@Umbraco.RenderMacro("listArticles")

src/AarhusWebDevCoopVbj/Views/Comment.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
}

src/AarhusWebDevCoopVbj/Views/Contactpage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
<h1>@Umbraco.Field("contactPageTitle")</h1>
	<p>@Umbraco.Field("contactPageContents")</p>
	@Html.Action("Index", "ContactFormSurface")

src/AarhusWebDevCoopVbj/Views/GridInfoPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

@CurrentPage.GetGridHtml("gridInfo")
	

src/AarhusWebDevCoopVbj/Views/Homepage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
<h1>@Umbraco.Field("homepagetitle")</h1>
	<p>@Umbraco.Field("homepagecontents")</p>
	<p>@Umbraco.RenderMacro("RenderCompletedProjects")</p>

src/AarhusWebDevCoopVbj/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
<p>@Umbraco.Field("textpagecontent")</p>
@if(!Members.GetCurrentLoginStatus().IsLoggedIn){
	@Html.Partial("login")
}else{
	<p>
		@Html.Partial("logout")	
	</p>
}

src/AarhusWebDevCoopVbj/Views/MacroPartials/RenderCompletedProjects.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
	@{ var selection = Umbraco.Content(1066).Children.OrderBy("createDate descending");}
	@*CurrentPage.Children.Where("Visible").OrderBy("CreateDate desc"); }*@
@* OrderBy() takes the property to sort by and optionally order desc/asc *@

  <h3>2 latest completed projects</h3>
<ul>
    @foreach (var item in selection.Take(2))
    {
		if(item.projectStatus == ("Completed")){
        	<li>
				<a href="@item.Url">@item.Name - @item.CreateDate</a>
				</li>	
		}
    }
</ul>

src/AarhusWebDevCoopVbj/Views/MacroPartials/TopNavigation.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@* The script is based on the script Jeavon Leopold wrote at http://our.umbraco.org/forum/developers/razor/56136-3-level-navigation?p=0  *@
@* Requires Bootstrap and some CSS incluede in the /css/bootstrap-submenu.css *@
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
	<a class="navbar-brand" href="/">AWD-COOP</a>
      
    </div>

    <!-- Menu  -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div class="container">
		<ul class="nav navbar-nav">
		
        @{
            var maxLevelForNav = 4;            
            var home = CurrentPage.AncestorsOrSelf(1).First();

            @RenderNavForNode(home, 1)

            foreach (var page in home.Children.Where("Visible"))
            {
                @RenderNavForNode(page, maxLevelForNav);
            }
        }
    	</ul>
		</div>
	
        </div><!--/.nav-collapse -->
      </div>
    </nav>


@helper RenderNavForNode(dynamic page, int maxLevel)
{
    var current = CurrentPage.Id == page.Id ? "active" : null;
    
	if (page.Children.Where("Visible").Any() && page.Level == 2 && page.Name == "Projects")
	{
		@:<li><a class="@current" href="@page.Url">@page.Name</a></li>
	}
	
	if (page.Children.Where("Visible").Any() && page.Level == 2 && page.Name == "Projects")
	{
		@:<li class="dropdown @current"><a href="@page.Url" class="dropdown-toggle @current" data-toggle="dropdown" role="button" aria-expanded="false">Project details<span class="caret"></span></a>
	}
	
	else if (page.Children.Where("Visible").Any() && page.Level > 2)
	{
		@:<li class="dropdown-submenu @current"><a class="@current" href="@page.Url">@page.Name</a>
	}
	else
	{
		@:<li><a class="@current" href="@page.Url">@page.Name</a></li>
	}
	
	
    if (page.Children.Where("Visible").Any() && page.Level < maxLevel)
    {
		
        <ul class="dropdown-menu" role="menu">
            @foreach (var subPage in page.Children.Where("Visible"))
            {
                @RenderNavForNode(subPage, maxLevel)
            }
        </ul>
    }
	
	
}

src/AarhusWebDevCoopVbj/Views/MacroPartials/generateMembersList.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{
var memberService =
ApplicationContext.Current.Services.MemberService;
var members = memberService.GetMembersByGroup("Active");
}

@foreach (var member in members)
{
<p>
@(member.GetValue("firstname") + " "
+ member.GetValue("lastname")) <br/>
@member.GetValue("address")<br />
@(member.GetValue("zip") + " "
+ member.GetValue("city"))<br />

</p>
}

src/AarhusWebDevCoopVbj/Views/MacroPartials/generateProspectsList.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{
var memberService =
ApplicationContext.Current.Services.MemberService;
var members = memberService.GetMembersByGroup("Prospect");
}
@foreach (var member in members)
{
<p>
@(member.GetValue("firstname") + " "
+ member.GetValue("lastname")) <br/>
</p>
}

src/AarhusWebDevCoopVbj/Views/MacroPartials/listArticles.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{ var selection = CurrentPage.Children.Where("Visible").OrderBy("CreateDate desc"); }
@* OrderBy() takes the property to sort by and optionally order desc/asc *@

<ul>
    @foreach (var item in selection)
    {
        <li><a href="@item.Url">@item.Name</a>
	@Umbraco.Truncate(@item.articleItemContent,100) <a href="@item.Url">Read More..</a>
    </li>
	<hr/>
    }
</ul>

src/AarhusWebDevCoopVbj/Views/MacroPartials/listProjects.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{ var selection = CurrentPage.Children.Where("Visible").OrderBy("Name"); }
@* OrderBy() takes the property to sort by *@

<ul>
    @foreach (var item in selection)
    {
        <li><a href="@item.Url">@item.Name</a>
			@Umbraco.Truncate(@item.projectItemContents,100) <a href="@item.Url">Read More..</a>
			</li>
			<hr/>
    }
</ul>

src/AarhusWebDevCoopVbj/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
}

<html>
<head>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	<link rel="stylesheet" href="/css/sticky-footer-navbar.css">
	<link rel="stylesheet" href="/css/styles.css">
</head>	
<body>
	@Umbraco.RenderMacro("TopNavigation")
	<div>
	<img src="@Umbraco.Field("headerimage")" class="img-responsive">
	</div>
    <div class="container">
        @RenderBody()
    </div>
	<footer class="footer">
	<div class="container">
        <p>Aarhus Web Dev Coop &copy; @DateTime.Now.Year</p>
      </div>
</footer>	
    <script src="~/scripts/jquery-1.9.1.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <script src="~/scripts/jquery.validate.min.js"></script>
    <script src="~/scripts/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>

src/AarhusWebDevCoopVbj/Views/Members.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
<h1>@Umbraco.Field("memberstitle")</h1>
	<p>@Umbraco.Field("memberscontents")</p>
	<hr/>
	<h2>Active members</h2>
@Umbraco.RenderMacro("generateMembersList")
	
	<h2>Prospects</h2>
	@Umbraco.RenderMacro("generateProspectsList")
	</div>

src/AarhusWebDevCoopVbj/Views/Partials/ContactForm.cshtml
@model AarhusWebDevCoopVbj.ViewModels.ContactForm
@{
    Layout = null;
}
@using System.ComponentModel.DataAnnotations;
@if (TempData["success"] == null)
{
    using (Html.BeginUmbracoForm("HandleFormSubmit", "ContactFormSurface", new object { }, new { @class = "form-horizontal" }))
    {
        <div class="form-group">
            @Html.LabelFor(m => m.Name, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name" })
                @Html.ValidationMessageFor(m => m.Name)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Email, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email" })
                @Html.ValidationMessageFor(m => m.Email)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Subject, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Subject, new { @class = "form-control", placeholder = "Subject" })
                @Html.ValidationMessageFor(m => m.Subject)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Message, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Message, new { @class = "form-control", placeholder = "Message" })
                @Html.ValidationMessageFor(m => m.Message)
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-6">
                <button id="contact-submit" type="submit" class="btn btn-primary input-medium pull-left">Send</button>
            </div>
        </div>
    }
}
else
{
    <p>Thank you for contacting us. We’ll be in touch soon!</p>
}

src/AarhusWebDevCoopVbj/Views/Partials/Grid/Bootstrap2.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

src/AarhusWebDevCoopVbj/Views/Partials/Grid/Bootstrap3.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="col-md-@s.grid column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

src/AarhusWebDevCoopVbj/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

src/AarhusWebDevCoopVbj/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates
@Html.Raw(Model.value)

src/AarhusWebDevCoopVbj/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

src/AarhusWebDevCoopVbj/Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.value != null)
{   
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        url += "?width=" + Model.editor.config.size.width;
        url += "&height=" + Model.editor.config.size.height;

        if(Model.value.focalPoint != null){
            url += "&center=" + Model.value.focalPoint.top +"," + Model.value.focalPoint.left;
            url += "&mode=crop";
        }
    }
    
    <img src="@url" alt="@Model.value.altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

src/AarhusWebDevCoopVbj/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))

src/AarhusWebDevCoopVbj/Views/Partials/Grid/Editors/Textstring.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.editor.config.markup != null)
{
    string markup = Model.editor.config.markup.ToString();

    markup = markup.Replace("#value#", Model.value.ToString());
    markup = markup.Replace("#style#", Model.editor.config.style.ToString());

    <text>
        @Html.Raw(markup)
    </text>
}
else
{
    <text>
        <div style="@Model.editor.config.style">@Model.value</div>
    </text>
}

src/AarhusWebDevCoopVbj/Views/Partials/login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using System.Web.Mvc.Html
@using ClientDependency.Core.Mvc
@using Umbraco.Web
@using Umbraco.Web.Models
@using Umbraco.Web.Controllers
@{
    var loginModel = new LoginModel();
    
    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();
    Html.RequiresJs("/umbraco_client/ui/jquery.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.min.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.unobtrusive.min.js");
}

@* NOTE: This RenderJsHere code should be put on your main template page where the rest of your script tags are placed *@
@Html.RenderJsHere()

@using (Html.BeginUmbracoForm<UmbLoginController>("HandleLogin"))
{
<fieldset id="contactVbj">
        
        @Html.ValidationSummary("loginModel", true)

		<div class="col-sm-2 control-label">
        	@Html.LabelFor(m => loginModel.Username)
		</div>
		<div class="col-sm-10">
        	@Html.TextBoxFor(m => loginModel.Username)
			@Html.ValidationMessageFor(m => loginModel.Username)
		</div>
        <br />
		<div class="col-sm-2 control-label">
        	@Html.LabelFor(m => loginModel.Password)
		</div>
		<div class="col-sm-10">
        	@Html.PasswordFor(m => loginModel.Password)
        	@Html.ValidationMessageFor(m => loginModel.Password)
		</div>
        <br />
		<div class="col-sm-offset-2 col-sm-10">
        	<button id="contact-submit" class="btn btn-primary input-medium pull-left">Login</button>
		</div>
    </fieldset>  
	
}

src/AarhusWebDevCoopVbj/Views/Partials/logout.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using System.Web.Mvc.Html
@using ClientDependency.Core.Mvc
@using Umbraco.Web
@using Umbraco.Web.Models
@using Umbraco.Web.Controllers
@{

var loginStatusModel = Members.GetCurrentLoginStatus();

Html.EnableClientValidation();
Html.EnableUnobtrusiveJavaScript();
Html.RequiresJs("/umbraco_client/ui/jquery.js");
Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.min.js");
Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.unobtrusive.min.js");

var logoutModel = new PostRedirectModel();
logoutModel.RedirectUrl = "/";

}

@Html.RenderJsHere()
@if (loginStatusModel.IsLoggedIn)
{

<p>You are currently logged in as @loginStatusModel.Name</p>


using (Html.BeginUmbracoForm<UmbLoginStatusController>("HandleLogout"))
{
    <fieldset>
        <legendend></legendend>
        <button>Logout</button>
    </fieldset>
    
    @Html.HiddenFor(m => logoutModel.RedirectUrl)
    }
}

src/AarhusWebDevCoopVbj/Views/ProjectsItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
<h1>@Umbraco.Field("projectItemTitle")</h1>
	<p>@Umbraco.Field("projectItemContents")</p>
	<div>Status: <i>@Umbraco.Field("projectStatus")</i></div>

src/AarhusWebDevCoopVbj/Views/ProjectsMain.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
<h1>@Umbraco.Field("projectsMainTitle")</h1>
	<p>@Umbraco.Field("projectsMainContents")</p>
	@Umbraco.RenderMacro("listProjects")

src/AarhusWebDevCoopVbj/Views/TextPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}